language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/pingcap/pd/.retools

go:
  - 1.12

script:
  - make ci

matrix:
  include:
  - go: 1.12
    install:
      - go get github.com/mattn/goveralls
    env:
      - TRAVIS_COVERAGE=1
      - CODECOV_TOKEN="60b4ec5a-ae12-4ec2-8dc7-ecf8266c4a03"
      - GOFLAGS=-p=8
    before_deploy: |
      function keep_alive() {
        while true; do
          echo -en "\a"
          sleep 5
        done
      }
      keep_alive &
    script:
      - make ci
    after_success:
      - travis_wait 10 make travis_coverage
      - mv overalls.coverprofile coverage.txt
      - bash <(curl -s https://codecov.io/bash)
